version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "22181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INNER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
  #     !!!Run in container
  #     kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --replication-factor 1 --partitions 1
  producer:
    build: ./producer/
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      KAFKA_ORDERS_PRODUCER_BOOTSTRAP-SERVERS: PLAINTEXT://kafka:9092
  consumer:
    depends_on:
      - kafka
    build: ./consumer/
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      KAFKA_ORDERS_CONSUMER_BOOTSTRAP-SERVERS: PLAINTEXT://kafka:9092

# docker-compose up -d --no-deps --build <service-name>


