spring:
  application:
    name: consumer
kafka:
  orders:
    consumer:
      bootstrap-servers: localhost:9092
      topic: orders
      group-id: myGroup1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,env,info
  endpoint:
    env:
      show-values: always